### ISSUE TITLE
Error could not find driver

### ISSUE THREAD

**Issue by gbast0s** [io238/laravel-iso-countries#7]
So I have run this command `composer require io238/laravel-iso-countries` and after that I just tried to call

`Country::find("pt")`, and `I got could not find driver (Connection: iso-countries, SQL: select * from \"countries\")`

I have a connection to MySQL database on .env, Am I missing something?

Also when I publish the config and I do not change anything and I try to run the command `php artisan db:seed countries:build` I got 

```
php artisan db:seed countries:build

   INFO  Seeding database.


   Illuminate\Contracts\Container\BindingResolutionException

  Target class [Database\Seeders\countries:build] does not exist.

  at vendor\laravel\framework\src\Illuminate\Container\Container.php:914
    910▕
    911▕         try {
    912▕             $reflector = new ReflectionClass($concrete);
    913▕         } catch (ReflectionException $e) {
  ➜ 914▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    915▕         }
    916▕
    917▕         // If the type is not instantiable, the developer is attempting to resolve
    918▕         // an abstract type such as an Interface or Abstract Class and there is

  1   vendor\laravel\framework\src\Illuminate\Container\Container.php:912
      ReflectionException::("Class "Database\Seeders\countries:build" does not exist")

  2   vendor\laravel\framework\src\Illuminate\Container\Container.php:912
      ReflectionClass::__construct("Database\Seeders\countries:build")
```

PHP version: 8.1.10
Laravel Framework 10.33.0

**Comment by gbast0s** [comment]
So I found it was a missing PHP extension

`extension=pdo_sqlite`

**Comment by io238** [comment]
Thanks for reporting this. I think it will make sense to show better error reporting, if Sqlite is not installed/enabled.

**Comment by SomeGuyNamedAlex** [comment]
I just want to come back on this, but for this part : 

"Also when I publish the config and I do not change anything and I try to run the command php artisan db:seed countries:build I got"

That error is not related to a missing extension (  Target class [Database\Seeders\countries:build] does not exist. ), but to the fact that the command in README is not valid :

Artisan just thinks countries:build is the seeder, instead of correctly running this as a second command !

Doing `php artisan db:seed  && php artisan countries:build
` would solve the 

@io238  could you change the README please 🥺
